/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuahangtienloi;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
public class TNKhachHang extends javax.swing.JFrame {
    
    private Connection conn; 
    String driver = "com.mysql.jdbc.Driver";
    /**
     * Creates new form TNKhachHang
     */
    public TNKhachHang() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        setPreferredSize(new Dimension(960, 580));
        JTableHeader tableHeader = tbThanhVien.getTableHeader();
        tableHeader.setBackground(new java.awt.Color(75, 139, 197));
        tableHeader.setForeground(Color.white);
        tableHeader.setFont(new Font("Tahoma", Font.PLAIN, 11));
        
        tbThanhVien.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbThanhVien.getColumnModel().getColumn(1).setPreferredWidth(500);
        tbThanhVien.getColumnModel().getColumn(2).setPreferredWidth(400);
        tbThanhVien.getColumnModel().getColumn(3).setPreferredWidth(300);
        tbThanhVien.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        try {
            //Load driver
            Class.forName(driver).newInstance();
            //conn = DriverManager.getConnection(url+dbName+strUnicode,userName,password);
           
            //Kết nối với Font chữ Unicode
            String urlUnicode = "jdbc:mysql://localhost:3306/quanlycuahang?user=root&password=&useUnicode=true&characterEncoding=utf8";
            //Tạo kết nối
            conn = DriverManager.getConnection(urlUnicode); 
            //-----
            System.out.println("Connected to the database");
           
            String SQL = "SELECT MaKH, TenKH, sdtKH, DiemTichLuy FROM khachhang";    
            
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(SQL);
            Vector data = null;
            rs.last();
            int count;
            count = rs.getRow();
            
            
            rs.beforeFirst(); 
            rs.next();
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("MaKH"));
                data.add(rs.getString("TenKH"));
                data.add(rs.getString("sdtKH"));
                data.add(rs.getInt("DiemTichLuy"));
                // Thêm một dòng vào table model
                DefaultTableModel defaultTable =(DefaultTableModel) tbThanhVien.getModel();
                defaultTable.addRow(data);
              }
            rs.close();
            stat.close();
            conn.close();
            }
            catch(SQLException se)
            {
                   se.printStackTrace();
            }catch(Exception e){
                    // Xu ly cac loi cho Class.forName
                    e.printStackTrace();
            }finally{

                   }// Ket thuc khoi finally
    }
 
    public javax.swing.JLabel getAccount(){
        return lbUserName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndexIcon = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        lbKhachHang = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        tfTenThanhVien = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        lbMKH = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThanhVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(956, 539));
        setPreferredSize(new java.awt.Dimension(973, 580));
        getContentPane().setLayout(null);

        IndexIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahangtienloi/Image/IconCT.png"))); // NOI18N
        IndexIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IndexIconMouseClicked(evt);
            }
        });
        getContentPane().add(IndexIcon);
        IndexIcon.setBounds(30, 20, 60, 60);

        jButton7.setBackground(new java.awt.Color(75, 139, 197));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Đăng Xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 220, 110, 40);

        jButton9.setBackground(new java.awt.Color(75, 139, 197));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Thành Viên");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 170, 110, 40);

        jButton8.setBackground(new java.awt.Color(75, 139, 197));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Bán Hàng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 120, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("!!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(910, 20, 20, 50);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahangtienloi/Image/IconReload.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(910, 60, 20, 20);

        lbUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUserName.setText("NVxx");
        getContentPane().add(lbUserName);
        lbUserName.setBounds(850, 20, 60, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Welcome");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(730, 20, 120, 50);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("QUẢN LÝ THÀNH VIÊN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 20, 180, 30);

        lbThongBao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbThongBao);
        lbThongBao.setBounds(30, 72, 170, 17);

        lbKhachHang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbKhachHang.setText("Tên: ");
        jPanel1.add(lbKhachHang);
        lbKhachHang.setBounds(20, 90, 40, 20);

        lbSDT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSDT.setText("SĐT: ");
        jPanel1.add(lbSDT);
        lbSDT.setBounds(30, 110, 30, 20);

        tfTenThanhVien.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tfTenThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenThanhVienActionPerformed(evt);
            }
        });
        jPanel1.add(tfTenThanhVien);
        tfTenThanhVien.setBounds(60, 92, 160, 17);

        tfSDT.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jPanel1.add(tfSDT);
        tfSDT.setBounds(60, 113, 160, 17);

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel1.add(btThem);
        btThem.setBounds(100, 280, 80, 30);

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btSua);
        btSua.setBounds(190, 280, 80, 30);

        lbMKH.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbMKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbMKH);
        lbMKH.setBounds(200, 72, 40, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(640, 130, 290, 340);

        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(tfTimKiem);
        tfTimKiem.setBounds(180, 100, 210, 20);

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 100, 60, 20);

        tbThanhVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên khách hàng", "SĐT", "Điểm tích lũy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThanhVien.setMinimumSize(new java.awt.Dimension(0, 0));
        tbThanhVien.setRowHeight(20);
        tbThanhVien.setRowMargin(5);
        tbThanhVien.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tbThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThanhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThanhVien);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 130, 430, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahangtienloi/Image/Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 956, 539);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndexIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IndexIconMouseClicked
        this.dispose();
        QLTrangChu reset = new QLTrangChu();
        reset.getAccount().setText(lbUserName.getText());
    }//GEN-LAST:event_IndexIconMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        DangNhap login = new DangNhap();
        login.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        TNKhachHang reset = new TNKhachHang();
        reset.getAccount().setText(lbUserName.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        TNBanHang reset = new TNBanHang();
        reset.getAccount().setText(lbUserName.getText());
        reset.gettfMaNhanVien().setEditable(false);
        reset.gettfMaNhanVien().setText(lbUserName.getText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        QLBanHang reset = new QLBanHang();
        reset.getAccount().setText(lbUserName.getText());
        reset.gettfMaNhanVien().setEditable(false);
        reset.gettfMaNhanVien().setText(lbUserName.getText());
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tfTenThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenThanhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenThanhVienActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed

        String TK = tfTenThanhVien.getText();
        String SDT = tfSDT.getText();

        try{
            Double.parseDouble(tfSDT.getText());
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Số điện thoại nhập không đúng định dạng!",  "", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(TK.equals("") | SDT.equals("")){
            JOptionPane.showMessageDialog(null, "Trường thông tin không hợp lệ!",  "", JOptionPane.WARNING_MESSAGE);
            this.dispose();
            QLKhachHang reset = new QLKhachHang();
            reset.getAccount().setText(lbUserName.getText());
        }
        else{
            String khprefixLessTen = "KH0";
            String khprefixEqMoreTen = "KH";

            try {

                String urlUnicode = "jdbc:mysql://localhost:3306/quanlycuahang?user=root&password=&useUnicode=true&characterEncoding=utf8";
                String driver = "com.mysql.jdbc.Driver";
                Class.forName(driver).newInstance();
                conn = (Connection) DriverManager.getConnection(urlUnicode);

                //Tạo mã kh bằng cách đếm dòng hiện tại, tạo string = HD_xx
                String SQL1 = "SELECT * FROM khachhang";
                Statement stat1 = conn.createStatement();
                ResultSet rs1 = stat1.executeQuery(SQL1);
                rs1.last();

                int countkh;//Thứ tự mã lớn nhất hiện tại
                countkh = rs1.getRow();//Do Mã bắt đầu từ 01, và có dòng rỗng 00
                String strcounthd = String.valueOf(countkh);
                String MHD="";
                if(countkh<10){
                    MHD = khprefixLessTen+strcounthd;
                }
                else{
                    MHD = khprefixEqMoreTen+strcounthd;
                }
                rs1.close();
                stat1.close();

                String SQL2="INSERT INTO khachhang VALUES(?,?,?,0)";

                PreparedStatement stat2 = conn.prepareStatement(SQL2);
                stat2.setString(1, MHD);
                stat2.setString(2, TK);
                stat2.setString(3, SDT);

                stat2.executeUpdate();
                conn.close();
                JOptionPane.showMessageDialog(null, "Thêm thành công",  "", JOptionPane.WARNING_MESSAGE);
                this.dispose();
                QLKhachHang reset = new QLKhachHang();
                reset.getAccount().setText(lbUserName.getText());

            } catch (SQLException ex) {
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed

        DefaultTableModel dsThanhVien =(DefaultTableModel) tbThanhVien.getModel();
        int SelectedRows = tbThanhVien.getSelectedRow();

        String MKH = lbMKH.getText();
        String TK = tfTenThanhVien.getText();
        String SDT = tfSDT.getText();

        try{
            Double.parseDouble(tfSDT.getText());
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Số điện thoại nhập không đúng định dạng!",  "", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String urlUnicode = "jdbc:mysql://localhost:3306/quanlycuahang?user=root&password=&useUnicode=true&characterEncoding=utf8";
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver).newInstance();
            conn = (Connection) DriverManager.getConnection(urlUnicode);

            String SQL1="UPDATE khachhang SET TenKH = ?, sdtKH = ? WHERE MaKH = ?";

            PreparedStatement stat1 = conn.prepareStatement(SQL1);

            stat1.setString(1, TK);
            stat1.setString(2, SDT);
            stat1.setString(3, MKH);

            stat1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cập nhật thành công",  "", JOptionPane.WARNING_MESSAGE);
            this.dispose();
            this.dispose();
            QLKhachHang reset = new QLKhachHang();
            reset.getAccount().setText(lbUserName.getText());

        } catch (SQLException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dsThanhVien =(DefaultTableModel) tbThanhVien.getModel();
        String keyword = tfTimKiem.getText();

        String keywordTKH = '%'+keyword+'%';

        dsThanhVien.setRowCount(0);

        try {
            //Load driver
            Class.forName(driver).newInstance();

            //Kết nối với Font chữ Unicode
            String urlUnicode = "jdbc:mysql://localhost:3306/quanlycuahang?user=root&password=&useUnicode=true&characterEncoding=utf8";
            //Tạo kết nối
            conn = DriverManager.getConnection(urlUnicode);
            //-----
            System.out.println("Connected to the database");
            String SQL = "SELECT * FROM khachhang WHERE MaKH = ? OR TenKH LIKE ? OR sdtKH = ?";

            PreparedStatement stat = conn.prepareStatement(SQL);
            stat.setString(1,keyword);
            stat.setString(2,keywordTKH);
            stat.setString(3,keyword);

            ResultSet rs = stat.executeQuery();

            Vector data = null;
            rs.last();
            rs.beforeFirst();
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("MaKH"));
                data.add(rs.getString("TenKH"));
                data.add(rs.getString("sdtKH"));
                data.add(rs.getInt("DiemTichLuy"));
                // Thêm một dòng vào table model
                dsThanhVien.addRow(data);
            }
            rs.close();
            stat.close();
            conn.close();
        }catch(SQLException se)
        {
            se.printStackTrace();
        }catch(Exception e){
            // Xu ly cac loi cho Class.forName
            e.printStackTrace();
        }finally{

        }// Ket thuc khoi finally
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThanhVienMouseClicked
        DefaultTableModel dsThanhVien =(DefaultTableModel)tbThanhVien.getModel();
        int SelectedRows = tbThanhVien.getSelectedRow();

        lbThongBao.setText("Chỉnh sửa thông tin khách hàng mã: ");
        lbMKH.setText(dsThanhVien.getValueAt(SelectedRows,0).toString());
        tfTenThanhVien.setText(dsThanhVien.getValueAt(SelectedRows,1).toString());
        tfSDT.setText(dsThanhVien.getValueAt(SelectedRows,2).toString());
    }//GEN-LAST:event_tbThanhVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TNKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TNKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TNKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TNKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TNKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IndexIcon;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbMKH;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTable tbThanhVien;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTenThanhVien;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
